//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPAS.FeatureTest.GlobalResolutionTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPAS.FeatureTest.GlobalResolutionTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caller Name, Culler Number, Caller National Code, Receiver Name, Receiver Number, Receiver National Code, Call Date, Call Duration, Call Type, Caller BTS, Caller Location,  Receiver BTS, Receiver Location
        ///Mahdi, 2007, 1001, Arya, 2002, 1002, 93/3/1, 5, Voice, 5001, 16, 5002, 18
        ///Arya, 2002, 1002, Mahdi, 2001, 1001, 93/3/1, 4, MultiMedia, 5003, 22, 5001, 16
        ///Mahdi, 2001, 1001, Hekmat, 2003, 1003, 93/3/2, 2, Voice, 5001, 16, 5003, 22
        ///Hekmat, 2003, 1003, Mostafa, 2004, 1004, 93/3/2, 1, MultiMedia, 5004, 2, 5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Internal_Resolution_Test_File_ {
            get {
                return ResourceManager.GetString("Internal Resolution Test File ", resourceCulture);
            }
        }
    }
}
