//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using GPAS.Workspace.Entities.KWLinks;

namespace GPAS.Workspace.Entities
{
    /// <summary>
    /// کلاس نگهداری و استفاده از رابطه (لینک) مبتنی بر وابستگی بین دو شی
    /// این نوع رابطه، از یک وابستگی (ریلیشنشیپ) بین شی مبدا و شی مقصد تشکیل شده است
    /// اجزای این کلاس با پیش فرض استفاده صحیح توسط استفاده کننده قابل تغییر هستند و مدیریت مقداردهی معتبر اجزای در دسترس آن، برعهده استفاده کننده می باشد
    /// </summary>
	public class RelationshipBasedKWLink : KWLink
	{
        /// <summary>
        /// وابستگی میان دو شی مبدا و مقصد را برمی گرداند یا مقداردهی می کند
        /// </summary>
		public virtual KWRelationship Relationship
		{
			get;
			set;
		}
        /// <summary>
        /// شی مبدا رابطه را برمی گرداند یا مقداردهی می کند
        /// </summary>
        public override KWObject Source
        {
            get;
            set;
        }
        /// <summary>
        /// شی مقصد رابطه را برمی گرداند یا مقداردهی می کند
        /// </summary>
        public override KWObject Target
        {
            get;
            set;
        }
        /// <summary>
        /// عنوان نمایشی برای رابطه را برمی گرداند؛ این مقدار همان عنوان نمایشی وابستگی بین دو شی مبدا و مقصد است.
        /// </summary>
        public override string Text
        {
            get { return Relationship.Description; }
        }
        /// <summary>
        /// نوع متناسب با رابطه برمی گرداند؛ این نوع همان نوع وابستگی بین دو شی مبدا و مقصد است.
        /// </summary>
        public override string TypeURI
        {
            get { return Relationship.TypeURI; }
        }
        /// <summary>
        /// جهت رابطه را برمی گرداند؛ این مقدار براساس جهت وابستگی بین دو شی مبدا و مقصد برگردانده می شود
        /// </summary>
        public override LinkDirection LinkDirection
        {
            get { return Relationship.LinkDirection; }
        }
        /// <summary>
        /// قابلیت ادغام/باز شدن برای رابطه را برمی گرداند؛ این قابلیت برای این نوع لینک همیشه غیرقابل ادغام است
        /// </summary>
        public override bool IsUnmergable
        {
            get { return false; }
        }

        public bool Equals(KWLink compairLink)
        {
            if (!(compairLink is RelationshipBasedKWLink))
                return false;
            return Relationship.Equals((compairLink as RelationshipBasedKWLink).Relationship);
        }

        public override bool Equals(object x)
        {
            if (x == null || !(x is RelationshipBasedKWLink))
                return false;

            return this.Equals(x as RelationshipBasedKWLink);
        }

        public override int GetHashCode()
        {            
            return Relationship.ID.GetHashCode();
        }
    }
}