//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPAS.Workspace.Presentation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string DefaultWorkspaceLastRunCulture {
            get {
                return ((string)(this["DefaultWorkspaceLastRunCulture"]));
            }
            set {
                this["DefaultWorkspaceLastRunCulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WorkspaceLastRunCulture {
            get {
                return ((string)(this["WorkspaceLastRunCulture"]));
            }
            set {
                this["WorkspaceLastRunCulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int QuickSearchUnpublishedResultMaxCount {
            get {
                return ((int)(this["QuickSearchUnpublishedResultMaxCount"]));
            }
            set {
                this["QuickSearchUnpublishedResultMaxCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public byte WorkspaceSideImport_MaximumImportingFilesCount {
            get {
                return ((byte)(this["WorkspaceSideImport_MaximumImportingFilesCount"]));
            }
            set {
                this["WorkspaceSideImport_MaximumImportingFilesCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte WorkspaceSideImport_MaximumSemiStructuredImportingFilesSizeInMegaBytes {
            get {
                return ((byte)(this["WorkspaceSideImport_MaximumSemiStructuredImportingFilesSizeInMegaBytes"]));
            }
            set {
                this["WorkspaceSideImport_MaximumSemiStructuredImportingFilesSizeInMegaBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int WorkspaceSideImport_MaximumImportingObjects {
            get {
                return ((int)(this["WorkspaceSideImport_MaximumImportingObjects"]));
            }
            set {
                this["WorkspaceSideImport_MaximumImportingObjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte ImportPreview_MaximumSampleRows {
            get {
                return ((byte)(this["ImportPreview_MaximumSampleRows"]));
            }
            set {
                this["ImportPreview_MaximumSampleRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public int ImportProcess_SingleImportingFileMaximumSizeInMegaBytes {
            get {
                return ((int)(this["ImportProcess_SingleImportingFileMaximumSizeInMegaBytes"]));
            }
            set {
                this["ImportProcess_SingleImportingFileMaximumSizeInMegaBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string WorkspaceSideImport_MaximumUnstructuredImportingFilesSizeInMegaBytes {
            get {
                return ((string)(this["WorkspaceSideImport_MaximumUnstructuredImportingFilesSizeInMegaBytes"]));
            }
            set {
                this["WorkspaceSideImport_MaximumUnstructuredImportingFilesSizeInMegaBytes"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}\\SavedMap")]
        public string SavedMapFolder {
            get {
                return ((string)(this["SavedMapFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}\\RecentCSA.xml")]
        public string CustomSearchAroundRecentLoadedFilePath {
            get {
                return ((string)(this["CustomSearchAroundRecentLoadedFilePath"]));
            }
        }
    }
}
