//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPAS.Workspace.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPAS.Workspace.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Types.
        /// </summary>
        internal static string Document_Types {
            get {
                return ResourceManager.GetString("Document_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Types.
        /// </summary>
        internal static string Entity_Types {
            get {
                return ResourceManager.GetString("Entity_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Types.
        /// </summary>
        internal static string Event_Types {
            get {
                return ResourceManager.GetString("Event_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive Or.
        /// </summary>
        internal static string Exclusive_Or {
            get {
                return ResourceManager.GetString("Exclusive_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has property type.
        /// </summary>
        internal static string Has_property_type {
            get {
                return ResourceManager.GetString("Has_property_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersection.
        /// </summary>
        internal static string Intersection {
            get {
                return ResourceManager.GetString("Intersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No set.
        /// </summary>
        internal static string No_set {
            get {
                return ResourceManager.GetString("No_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Types.
        /// </summary>
        internal static string Object_Types {
            get {
                return ResourceManager.GetString("Object_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects matching one of the defined Property-Values:.
        /// </summary>
        internal static string ObjectsMatchingOneOfTheDefinedPropertyValues_ {
            get {
                return ResourceManager.GetString("ObjectsMatchingOneOfTheDefinedPropertyValues_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of type:.
        /// </summary>
        internal static string Of_type_ {
            get {
                return ResourceManager.GetString("Of_type_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Type.
        /// </summary>
        internal static string Property_Type {
            get {
                return ResourceManager.GetString("Property_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract Left.
        /// </summary>
        internal static string Subtract_Left {
            get {
                return ResourceManager.GetString("Subtract_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract Right.
        /// </summary>
        internal static string Subtract_Right {
            get {
                return ResourceManager.GetString("Subtract_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Union.
        /// </summary>
        internal static string Union {
            get {
                return ResourceManager.GetString("Union", resourceCulture);
            }
        }
    }
}
