//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPAS.DataImport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPAS.DataImport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file not found..
        /// </summary>
        internal static string Excel_file_not_found {
            get {
                return ResourceManager.GetString("Excel_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find matches to this property.
        /// </summary>
        internal static string InternalResolutionOption_FindMatch_Description {
            get {
                return ResourceManager.GetString("InternalResolutionOption_FindMatch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will ignored in resolution.
        /// </summary>
        internal static string InternalResolutionOption_Ignorable_Description {
            get {
                return ResourceManager.GetString("InternalResolutionOption_Ignorable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must match to resolve.
        /// </summary>
        internal static string InternalResolutionOption_MustMatch_Description {
            get {
                return ResourceManager.GetString("InternalResolutionOption_MustMatch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Access file has a Table/View with too much columns; Table/View &apos;{0}&apos; has {1} columns but the limit is {2}..
        /// </summary>
        internal static string The_Access_file_has_a_Table_or_View_with_too_much_columns {
            get {
                return ResourceManager.GetString("The_Access_file_has_a_Table_or_View_with_too_much_columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Excel file has a worksheet with too much columns; Sheet &apos;{0}&apos; has {1} columns but the limit is {2}..
        /// </summary>
        internal static string The_Excel_file_has_a_worksheet_with_too_much_columns_ {
            get {
                return ResourceManager.GetString("The_Excel_file_has_a_worksheet_with_too_much_columns_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load Excel file.
        /// </summary>
        internal static string Unable_to_load_Excel_file {
            get {
                return ResourceManager.GetString("Unable_to_load_Excel_file", resourceCulture);
            }
        }
    }
}
