//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPAS.Dispatch.AdminTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPAS.Dispatch.AdminTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add IP-Geo Information.
        /// </summary>
        public static string Add_IPGeo_Information {
            get {
                return ResourceManager.GetString("Add_IPGeo_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Tools.
        /// </summary>
        public static string Administrator_Tools {
            get {
                return ResourceManager.GetString("Administrator_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the group?.
        /// </summary>
        public static string Are_You_Sure_You_Want_To_Delete_The_Group {
            get {
                return ResourceManager.GetString("Are_You_Sure_You_Want_To_Delete_The_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Time.
        /// </summary>
        public static string Begin_Time {
            get {
                return ResourceManager.GetString("Begin_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse File.
        /// </summary>
        public static string Browse_File {
            get {
                return ResourceManager.GetString("Browse_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string Busy {
            get {
                return ResourceManager.GetString("Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User Details.
        /// </summary>
        public static string Change_User_Details {
            get {
                return ResourceManager.GetString("Change_User_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classifications:.
        /// </summary>
        public static string Classifications {
            get {
                return ResourceManager.GetString("Classifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidential.
        /// </summary>
        public static string Confidential {
            get {
                return ResourceManager.GetString("Confidential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string Create_Group {
            get {
                return ResourceManager.GetString("Create_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string Create_User {
            get {
                return ResourceManager.GetString("Create_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created_By.
        /// </summary>
        public static string Created_By {
            get {
                return ResourceManager.GetString("Created_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Time.
        /// </summary>
        public static string Created_Time {
            get {
                return ResourceManager.GetString("Created_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Page.
        /// </summary>
        public static string Current_Page {
            get {
                return ResourceManager.GetString("Current_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Permission.
        /// </summary>
        public static string Define_Permission {
            get {
                return ResourceManager.GetString("Define_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Group.
        /// </summary>
        public static string Delete_Group {
            get {
                return ResourceManager.GetString("Delete_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Address.
        /// </summary>
        public static string E_Mail_Address {
            get {
                return ResourceManager.GetString("E_Mail_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Personal Info.
        /// </summary>
        public static string Edit_Personal_Info {
            get {
                return ResourceManager.GetString("Edit_Personal_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string End_Time {
            get {
                return ResourceManager.GetString("End_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path:.
        /// </summary>
        public static string File_Path {
            get {
                return ResourceManager.GetString("File_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Page.
        /// </summary>
        public static string First_Page {
            get {
                return ResourceManager.GetString("First_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Full_Name {
            get {
                return ResourceManager.GetString("Full_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Description.
        /// </summary>
        public static string Group_Description {
            get {
                return ResourceManager.GetString("Group_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Field Can Not Be Null Or Empty.
        /// </summary>
        public static string Group_Field_Can_Not_Be_Null_Or_Empty {
            get {
                return ResourceManager.GetString("Group_Field_Can_Not_Be_Null_Or_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string Group_Name {
            get {
                return ResourceManager.GetString("Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name:.
        /// </summary>
        public static string Group_Name_Colon {
            get {
                return ResourceManager.GetString("Group_Name_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizon Server.
        /// </summary>
        public static string Horizon_Server {
            get {
                return ResourceManager.GetString("Horizon_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizon index manager.
        /// </summary>
        public static string HorizonIndexManager {
            get {
                return ResourceManager.GetString("HorizonIndexManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import IP-Geo Information File.
        /// </summary>
        public static string Import_IPGeo_Information_File {
            get {
                return ResourceManager.GetString("Import_IPGeo_Information_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexes Stability:.
        /// </summary>
        public static string Indexes_Stability {
            get {
                return ResourceManager.GetString("Indexes_Stability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP:.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs Status:.
        /// </summary>
        public static string Jobs_Status {
            get {
                return ResourceManager.GetString("Jobs_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Page.
        /// </summary>
        public static string Last_Page {
            get {
                return ResourceManager.GetString("Last_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude:.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading jobs status.
        /// </summary>
        public static string Loading_Jobs_Status {
            get {
                return ResourceManager.GetString("Loading_Jobs_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Synchronization Status..
        /// </summary>
        public static string Loading_Search_Servers_Synchronization_Status {
            get {
                return ResourceManager.GetString("Loading_Search_Servers_Synchronization_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading User Accounts Information..
        /// </summary>
        public static string Loading_User_Accounts_Information {
            get {
                return ResourceManager.GetString("Loading_User_Accounts_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login field can not be null or empty.
        /// </summary>
        public static string Login_Field_Can_Not_Be_Null_Or_Empty {
            get {
                return ResourceManager.GetString("Login_Field_Can_Not_Be_Null_Or_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude:.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Of.
        /// </summary>
        public static string Member_Of {
            get {
                return ResourceManager.GetString("Member_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Users.
        /// </summary>
        public static string Member_Users {
            get {
                return ResourceManager.GetString("Member_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name_WithColon {
            get {
                return ResourceManager.GetString("Name_WithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string Next_Page {
            get {
                return ResourceManager.GetString("Next_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Member Of.
        /// </summary>
        public static string Not_Member_Of {
            get {
                return ResourceManager.GetString("Not_Member_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm password is not matched.
        /// </summary>
        public static string Password_And_Confirm_Password_Is_Not_Matched {
            get {
                return ResourceManager.GetString("Password_And_Confirm_Password_Is_Not_Matched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password or Confirm password is empty.
        /// </summary>
        public static string Password_Or_Confirm_Password_Is_Empty {
            get {
                return ResourceManager.GetString("Password_Or_Confirm_Password_Is_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordWithColon {
            get {
                return ResourceManager.GetString("PasswordWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission:.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        public static string Please_Wait {
            get {
                return ResourceManager.GetString("Please_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string Previous_Page {
            get {
                return ResourceManager.GetString("Previous_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh jobs status.
        /// </summary>
        public static string Refresh_jobs_status {
            get {
                return ResourceManager.GetString("Refresh_jobs_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Time.
        /// </summary>
        public static string Register_Time {
            get {
                return ResourceManager.GetString("Register_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Data.
        /// </summary>
        public static string Remove_All_Data {
            get {
                return ResourceManager.GetString("Remove_All_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing All Data ....
        /// </summary>
        public static string Removing_All_Data {
            get {
                return ResourceManager.GetString("Removing_All_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted.
        /// </summary>
        public static string Restricted {
            get {
                return ResourceManager.GetString("Restricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Server.
        /// </summary>
        public static string Search_Server {
            get {
                return ResourceManager.GetString("Search_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret:.
        /// </summary>
        public static string Secret {
            get {
                return ResourceManager.GetString("Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Securing Connection....
        /// </summary>
        public static string Securing_Connection_ {
            get {
                return ResourceManager.GetString("Securing_Connection_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password did not match..
        /// </summary>
        public static string String_ConfirmationPasswordDidNotMatch {
            get {
                return ResourceManager.GetString("String_ConfirmationPasswordDidNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all indexes?.
        /// </summary>
        public static string String_DeleteAllHorizonIndexes {
            get {
                return ResourceManager.GetString("String_DeleteAllHorizonIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the index?.
        /// </summary>
        public static string String_DeleteHorizonIndex {
            get {
                return ResourceManager.GetString("String_DeleteHorizonIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the user?.
        /// </summary>
        public static string String_DeleteUser {
            get {
                return ResourceManager.GetString("String_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        public static string String_DeleteUserTitle {
            get {
                return ResourceManager.GetString("String_DeleteUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid ip address.
        /// </summary>
        public static string String_InvalidIpAddress {
            get {
                return ResourceManager.GetString("String_InvalidIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid value.
        /// </summary>
        public static string String_InvalidValue {
            get {
                return ResourceManager.GetString("String_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently remove all data?.
        /// </summary>
        public static string String_RemoveAllData {
            get {
                return ResourceManager.GetString("String_RemoveAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove data completely, read administrative event logs for more details..
        /// </summary>
        public static string String_RemoveDataFailed {
            get {
                return ResourceManager.GetString("String_RemoveDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Data remove from servers..
        /// </summary>
        public static string String_RemoveDataSuccess {
            get {
                return ResourceManager.GetString("String_RemoveDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated.
        /// </summary>
        public static string Terminated {
            get {
                return ResourceManager.GetString("Terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The groupname is already exist.
        /// </summary>
        public static string The_groupname_is_already_exist {
            get {
                return ResourceManager.GetString("The_groupname_is_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Login-Name is already exist..
        /// </summary>
        public static string The_username_is_already_exist {
            get {
                return ResourceManager.GetString("The_username_is_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Secret.
        /// </summary>
        public static string Top_Secret {
            get {
                return ResourceManager.GetString("Top_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsynchronized Indexes :.
        /// </summary>
        public static string Unsynchronized_Indexes {
            get {
                return ResourceManager.GetString("Unsynchronized_Indexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAccountControlPrompt.
        /// </summary>
        public static string User_Account_Control_Prompt {
            get {
                return ResourceManager.GetString("User_Account_Control_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName:.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect.
        /// </summary>
        public static string UserName_Or_Password_Is_Incorrect {
            get {
                return ResourceManager.GetString("UserName_Or_Password_Is_Incorrect", resourceCulture);
            }
        }
    }
}
