//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Xml.Serialization;

namespace GPAS.Workspace.Entities
{
    /// <summary>
    /// کلاس نگهداری و استفاده از شی
    /// اجزای این کلاس با پیش فرض استفاده صحیح توسط استفاده کننده قابل تغییر هستند و مدیریت مقداردهی معتبر اجزای در دسترس آن، برعهده استفاده کننده می باشد
    /// </summary>
	public class KWObject : IEqualityComparer, IComparer
    {
        public KWObject()
        {

        }
        private KWProperty displayName = null;

        /// <summary>
        /// عنوان نمایشی شی را برمی گرداند یا مقداردهی می کند
        /// </summary>
        [XmlIgnore]
        public virtual KWProperty DisplayName
        {
            get
            {
                return displayName;
            }
            set
            {
                displayName = value;
            }
        }

        /// <summary>
        /// نوع شی را براساس تعاریف هستان شناسی برمی گرداند یا مقداردهی می کند
        /// </summary>
        public virtual string TypeURI
        {
            get;
            set;
        }
        /// <summary>
        /// شناسه شی را براساس مقدار آن در مخزن داده ها برمی گرداند یا مقداردهی می کند!
        /// </summary>
        public virtual long ID
        {
            get;
            set;
        }

        public long MasterId
        {
            get;
            set;
        }

        public bool Equals(KWObject otherObject)
        {
            return ID == otherObject.ID;
        }

        public KWObject ResolvedTo
        {
            get;
            set;
        }

        public bool IsMaster
        {
            get;
            set;
        }

        public bool IsSlave
        {
            get;
            set;
        }

        public KWObjectMaster KWObjectMaster
        {
            get;
            set;
        }

        public int GetHashCode(object obj)
        {
            if (obj == null || !(obj is KWObject))
                return 0;
            else
                return GetHashCode();
        }

        public new bool Equals(object x, object y)
        {
            return ReferenceEquals(x, y);
        }

        public int Compare(object x, object y)
        {
            if (x == null || !(x is KWObject)
                || y == null || !(y is KWObject))
            {
                throw new ArgumentException();
            }
            return (x as KWObject).GetHashCode() - (y as KWObject).GetHashCode();
        }

        public string GetObjectLabel()
        {
            return (displayName != null)
                ? displayName.Value
                : Properties.Resources._No_Title_;
        }
    }
}