//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GPAS.Workspace.Entities.KWLinks;

namespace GPAS.Workspace.Entities
{
    using System;

    /// <summary>
    /// کلاس نگهداری و استفاده از وابستگی (ریلیشنشیپ) بین دو شی
    /// اجزای این کلاس با پیش فرض استفاده صحیح توسط استفاده کننده قابل تغییر هستند و مدیریت مقداردهی معتبر اجزای در دسترس آن، برعهده استفاده کننده می باشد
    /// </summary>
	public class KWRelationship
    {
        /// <summary>
        /// شناسه یکتای وابستگی را برمی گرداند یا مقداردهی می کند
        /// </summary>
		public virtual long ID
        {
            get;
            set;
        }
        /// <summary>
        /// توضیحات وابستگی را برمی گرداند یا مقداردهی می کند
        /// </summary>
		public virtual string Description
        {
            get;
            set;
        }
        /// <summary>
        /// زمان شروع وابستگی را برمی گرداند یا مقداردهی می کند
        /// </summary>
		public virtual DateTime? TimeBegin
        {
            get;
            set;
        }
        /// <summary>
        /// زمان پایان وابستگی را برمی گرداند یا مقداردهی می کند
        /// </summary>
		public virtual DateTime? TimeEnd
        {
            get;
            set;
        }
        /// <summary>
        /// نوع وابستگی را براساس تعاریف هستان شناسی برمی گرداند یا مقداردهی می کند
        /// </summary>
        public string TypeURI
        {
            get;
            set;
        }
        /// <summary>
        /// جهت وابستگی را برمی گرداند یا مقداردهی می کند
        /// </summary>
        public LinkDirection LinkDirection
        {
            get;
            set;
        }
        public long? DataSourceId
        {
            get;
            set;
        }
        public bool Equals(KWRelationship relationshipToCompair)
        {
            return ID == relationshipToCompair.ID;
        }

        public event EventHandler<EventArgs> Deleted;
        public void OnDeleted()
        {
            if (Deleted != null)
                Deleted(this, EventArgs.Empty);
        }
    }
}