//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPAS.HistogramViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPAS.HistogramViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less.
        /// </summary>
        internal static string ExpandRowCommands_Less {
            get {
                return ResourceManager.GetString("ExpandRowCommands_Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string ExpandRowCommands_More {
            get {
                return ResourceManager.GetString("ExpandRowCommands_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string ExpandRowCommands_ShowAll {
            get {
                return ResourceManager.GetString("ExpandRowCommands_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram request canceled by user.
        /// </summary>
        internal static string Histogram_Request_Canceled_By_User {
            get {
                return ResourceManager.GetString("Histogram_Request_Canceled_By_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item to show..
        /// </summary>
        internal static string NoItemPropmts_NotItemToShowPrompt {
            get {
                return ResourceManager.GetString("NoItemPropmts_NotItemToShowPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property group add to Histogram..
        /// </summary>
        internal static string ReadyPrompts_AGroupAdded {
            get {
                return ResourceManager.GetString("ReadyPrompts_AGroupAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram content cleared..
        /// </summary>
        internal static string ReadyPrompts_HistogramCleared {
            get {
                return ResourceManager.GetString("ReadyPrompts_HistogramCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} property groups added to Histogram..
        /// </summary>
        internal static string ReadyPrompts_MoreThanOneGroupAdded {
            get {
                return ResourceManager.GetString("ReadyPrompts_MoreThanOneGroupAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ReadyPrompts_SimpleReadyPrompt {
            get {
                return ResourceManager.GetString("ReadyPrompts_SimpleReadyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} item(s) selected..
        /// </summary>
        internal static string ReadyPrompts_SomeItemsSelected {
            get {
                return ResourceManager.GetString("ReadyPrompts_SomeItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait... [{0}/{1}].
        /// </summary>
        internal static string WaitingPrompts_DeterminedWaitingPrompt {
            get {
                return ResourceManager.GetString("WaitingPrompts_DeterminedWaitingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ready! Please wait....
        /// </summary>
        internal static string WaitingPrompts_UnableToResponseWhileWorkNotCompleted {
            get {
                return ResourceManager.GetString("WaitingPrompts_UnableToResponseWhileWorkNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string WaitingPrompts_UndeterminedWaitingPrompt {
            get {
                return ResourceManager.GetString("WaitingPrompts_UndeterminedWaitingPrompt", resourceCulture);
            }
        }
    }
}
